Employee career analysis

In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [7]:
import plotly.io as pio
pio.renderers.default="iframe"

In [8]:
df=pd.read_csv("python day 24 Your Career Aspirations of GenZ.csv")
df

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,India,605008,Male,"People from my circle, but not family members","Yes, I will earn and do that",Will work for 3 years or more,No,Will NOT work for them,7,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Learning by obser...","Design and Creative strategy in any company, B...",Manager who sets goal and helps me achieve it,Work with more than 10 people in my team
231,India,722207,Male,"People from my circle, but not family members",No I would not be pursuing Higher Education ou...,"This will be hard to do, but if it is the righ...",Yes,Will work for them,5,Hybrid Working Environment with less than 3 da...,Employer who rewards learning and enables that...,"Learning by observing others, Trial and error ...","Business Operations in any organization, Look ...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
232,India,604102,Female,People who have changed the world for better,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,4,Hybrid Working Environment with less than 10 d...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...","Design and Creative strategy in any company, B...",Manager who sets goal and helps me achieve it,Work with more than 10 people in my team
233,India,122002,Male,People who have changed the world for better,"Yes, I will earn and do that","No way, 3 years with one employer is crazy",No,Will NOT work for them,7,Hybrid Working Environment with less than 15 d...,Employer who rewards learning and enables that...,"Self Paced Learning Portals, Instructor or Exp...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
234,India,605102,Female,My Parents,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",Yes,Will work for them,5,Every Day Office Environment,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Desig...",Manager who sets targets and expects me to ach...,Work with 7 to 10 or more people in my team

In [4]:
df.head()

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."

In [9]:
df.columns

Index(['Your Current Country.', 'Your Current Zip Code / Pin Code',
       'Your Gender',
       'Which of the below factors influence the most about your career aspirations ?',
       'Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.',
       'How likely is that you will work for one employer for 3 years or more ?',
       'Would you work for a company whose mission is not clearly defined and publicly posted.',
       'How likely would you work for a company whose mission is misaligned with their public actions or even their product ?',
       'How likely would you work for a company whose mission is not bringing social impact ?',
       'What is the most preferred working environment for you.',
       'Which of the below Employers would you work with.',
       'Which type of learning environment that you are most likely to work in ?',
       'Which of the below careers looks close to your Aspirational job ?',
       'What type of Manager would you work without looking into your watch ?',
       'Which of the following setup you would like to work ?'],
      dtype='object')

In [20]:

country=df['Your Current Country.'].value_counts()
label=country.index
counts=country.values
colors=['red','yellow','lightgreeen','blue']
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="current country")
fig.update_traces(hoverinfo='label+value',textinfo='percent',marker=dict(colors=colors,line=dict(color="black",width=1)))
fig.show()

careen inspiration

In [22]:
question=df['Which of the below factors influence the most about your career aspirations ?'].value_counts()
label=question.index
counts=question.values
colors=['red','yellow','lightgreeen','blue']
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="factor influencing career")
fig.update_traces(hoverinfo='label+value',textinfo='percent',marker=dict(colors=colors,line=dict(color="black",width=1)))
fig.show()

people want to study outside the india

In [34]:
question2=df['Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.'].value_counts()
label=question2.index
counts=question2.values
colors=['purple','neon','gold']
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.")
fig.update_traces(hoverinfo='label+value',textinfo='percent',marker=dict(colors=colors,line=dict(color="black",width=1)))
fig.show()

switching experience

In [33]:
question3=df['How likely is that you will work for one employer for 3 years or more ?'].value_counts()
label=question3.index
counts=question3.values
colors=['brown','pink','gold']
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text="How likely is that you will work for one employer for 3 years or more ?")
fig.update_traces(hoverinfo='label+value',textinfo='percent',marker=dict(colors=colors,line=dict(color="black",width=1)))
fig.show()

In [32]:
question4=df['What is the most preferred working environment for you.'].value_counts()
label=question4.index
counts=question4.values
color=('aqua','red','darkgreen')
fig=go.Figure(data=[go.Pie(labels=label,values=counts)])
fig.update_layout(title_text='What is the most preferred working environment for you.')
fig.update_traces(hoverinfo='label+percent',textinfo='percent',marker=dict(colors=colors,line=dict(color="black",width=1)))
fig.show()